services:
  db-test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: pismo_visa_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway-test:
    image: flyway/flyway:10-alpine
    platform: linux/amd64
    command: migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://db-test:5432/pismo_visa_test
      FLYWAY_USER: ${POSTGRES_USER:-postgres}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway.toml:/flyway/flyway.toml
    depends_on:
      db-test:
        condition: service_healthy
