services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pismo-network

  flyway:
    image: flyway/flyway:10-alpine
    platform: linux/amd64
    command: migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway.toml:/flyway/flyway.toml
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pismo-network

volumes:
  postgres_data:

networks:
  pismo-network:
    name: pismo-network
